{% set name = "sqlalchemy-mate" %}
{% set version = "1.4.28.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_mate-{{ version }}.tar.gz
  sha256: bff5fe2a5c965f5c438fe907360abe90eb4de33028c389ae43556194826924dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - prettytable
    - sqlalchemy >=1.4.1,<2.0.0

test:
  imports:
    - sqlalchemy_mate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MacHu-GWU/sqlalchemy_mate-project
  summary: A library extend sqlalchemy module, makes CRUD easier.
  license: MIT
  license_file: LICENSE.txt
  description: |
    A sweet syntax sugar library to simplify your effort in writing `sqlalchemy` code.

    PyPI: [https://pypi.org/project/sqlalchemy-mate/](https://pypi.org/project/sqlalchemy-mate/)

  doc_url: https://sqlalchemy-mate.readthedocs.io/index.html
  dev_url: https://github.com/MacHu-GWU/sqlalchemy_mate-project

extra:
  recipe-maintainers:
    - sugatoray
